import { ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

export default function About() {
  return (
    <div className="site-shell mx-auto max-w-[1440px] px-5 pb-24 pt-36 md:px-10 md:pb-36">
      <section className="grid gap-12 border-b border-line pb-20 md:grid-cols-[.8fr_1.2fr] md:items-end"><p className="eyebrow">Sobre mim / experiência</p><div><h1 className="max-w-5xl font-display text-[clamp(5.5rem,13vw,11rem)] uppercase leading-[.77] tracking-[-.065em] text-paper">Quem está<br /><span className="text-white/45">por trás</span><br />dos cortes.</h1></div></section>
      <section className="grid gap-14 py-20 md:grid-cols-[1fr_1fr] md:items-center md:py-32"><motion.div initial={{ opacity: 0, x: -18 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="relative aspect-square overflow-hidden border border-white/10 md:aspect-[4/5]"><img src="/images/pedro-no-laptop.jpeg" alt="Pedro Rocha trabalhando em um laptop" className="h-full w-full object-cover grayscale-[15%] transition duration-700 hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-ink/55 to-transparent" /><p className="absolute bottom-5 left-5 text-[10px] uppercase tracking-[.2em] text-paper">Pedro Rocha / Fortaleza</p></motion.div><div><p className="eyebrow">A pessoa por trás do processo</p><p className="mt-8 max-w-xl text-2xl leading-snug tracking-[-.03em] text-paper md:text-4xl">Edição de vídeo para marcas pessoais que querem ser lembradas pelo que dizem — e pelo jeito como dizem.</p><div className="mt-8 max-w-lg space-y-5 text-sm leading-7 text-white/50"><p>Pedro Rocha é editor de vídeo com mais de 2 anos de experiência, especializado em conteúdo para marcas pessoais, profissionais liberais e projetos digitais.</p><p>Já participou da edição de mais de 2.000 vídeos e de mais de 50 perfis, atuando com médicos, advogados, influenciadores, agências de marketing e lançamentos digitais.</p><p>O trabalho cruza direção visual, ritmo e uma atenção quase obsessiva ao detalhe que faz uma fala parecer presença.</p></div><Link to="/contato" className="mt-10 inline-flex items-center gap-2 border-b border-sky pb-2 text-[10px] uppercase tracking-[.2em] text-sky hover:text-paper">Conversar sobre um projeto <ArrowUpRight size={15} /></Link></div></section>
      <section className="border-y border-line py-20 md:py-28"><div className="grid grid-cols-3 gap-4"><div><p className="font-display text-6xl leading-none tracking-[-.06em] text-paper md:text-9xl">2.000+</p><p className="mt-3 max-w-[150px] text-[10px] uppercase leading-4 tracking-[.18em] text-white/40">vídeos editados</p></div><div><p className="font-display text-6xl leading-none tracking-[-.06em] text-paper md:text-9xl">50+</p><p className="mt-3 max-w-[150px] text-[10px] uppercase leading-4 tracking-[.18em] text-white/40">perfis e projetos</p></div><div><p className="font-display text-6xl leading-none tracking-[-.06em] text-paper md:text-9xl">2+</p><p className="mt-3 max-w-[150px] text-[10px] uppercase leading-4 tracking-[.18em] text-white/40">anos de experiência</p></div></div></section>
      <section className="py-20 md:py-28"><p className="eyebrow">Clientes e parcerias</p><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 text-3xl tracking-[-.04em] text-white/55 md:text-6xl"><span>Pedro Assad</span><span>Flávia Marinho</span><span>Sublime</span><span>Verz</span><span>ALP</span><span>Luana Pavanate</span></div></section>
    </div>
  );
}
